travis:
  secure:
    BINSTAR_TOKEN: lJ/o4MfzfZXHc5gzWplex41PXa42SU9AA74q4j8x5gBMkHHf46eWWcpkeUXK9nZtPSBcrhmhirwxA86bem0g+2qBq6jblIk4ZLWA4hTZjGXpAyQUb+wggK4B/v8rZ9MkVu/xGPbuZi4FC5cmmZ9eqZuIWumXEH7GTY7Dt5JhwpkbvbKlG3ZC0++my6bJCkrqE8xoSdjohhGfIyLhOIiCh2RFB9AnypKWXXS48KfBnRggqBUdVJw0LS6em4ro8/Ie0qZ+Y302Gw4+znwY5tCxHrrsrC7NdsxWpN5P3SUto6SOZLIGay7SowJwIwo2KKQaGPz0v7CD/ERsU26M9qsWABJupcU8eDNLswRUGH4SAkvV1E36fIQMESnr8/PGsicvuR8FpxOAGR0M0DqHoZBvV3kPU/1SNUt6lC9OAzjMoP/si0qswevv/U9G/hPh7IEnTjAB51uw4Q5rXZa2gMHhltYjShG1aWBgAz02FfipsanySn8/n/ttDIKfw7Oss7W9R3+V683riqGWIVZNDPXgi7SklUz1BfIH1jcOLStTNu7+COAkGy5Pe1Tgt5u40LJWoP9gbFnNSvZVeE4rOLgfPgs0zxlxegzhIC1+t8c/N7PiW8Reov6couTe7BzQM7355xgmaAS7zk96b1lkkZlMqvNgLXDq2hXjovBGZTkzSDA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
